In [1]:
library(readr)
library(readxl)

Warning message:
"package 'readr' was built under R version 3.6.3"Warning message:
"package 'readxl' was built under R version 3.6.3"

In [2]:
readr_example()

[1] "challenge.csv"     "epa78.txt"         "example.log"
[4] "fwf-sample.txt"    "massey-rating.txt" "mtcars.csv"
[7] "mtcars.csv.bz2"    "mtcars.csv.zip"

In [3]:
mtcars <- read_csv(readr_example('mtcars.csv'))
mtcars

-- Column specification ------------------------------------------------------------------------------------------------
cols(
  mpg = col_double(),
  cyl = col_double(),
  disp = col_double(),
  hp = col_double(),
  drat = col_double(),
  wt = col_double(),
  qsec = col_double(),
  vs = col_double(),
  am = col_double(),
  gear = col_double(),
  carb = col_double()
)

   mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
1  21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
2  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
3  22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
4  21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
5  18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
6  18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
7  14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
8  24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
9  22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
10 19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
11 17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
12 16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
13 17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
14 15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
15 10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
16 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
17 14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
18 32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
19 30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
20 33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
21 21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
22 15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
23 15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
24 13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
25 19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
26 27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
27 26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
28 30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
29 15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
30 19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
31 15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
32 21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [4]:
mtcars[1:10,]

   mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
1  21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
2  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
3  22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
4  21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
5  18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
6  18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
7  14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
8  24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
9  22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
10 19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4

In [5]:
read_log(readr_example('example.log'))

-- Column specification ------------------------------------------------------------------------------------------------
cols(
  X1 = col_character(),
  X2 = col_logical(),
  X3 = col_character(),
  X4 = col_character(),
  X5 = col_character(),
  X6 = col_double(),
  X7 = col_double()
)

  X1           X2 X3                 X4
1 172.21.13.45 NA Microsoft\\JohnDoe 08/Apr/2001:17:39:04 -0800
2 127.0.0.1    NA frank              10/Oct/2000:13:55:36 -0700
  X5                                               X6  X7
1 GET /scripts/iisadmin/ism.dll?http/serv HTTP/1.0 200 3401
2 GET /apache_pb.gif HTTP/1.0                      200 2326

In [6]:
sheets = readxl_example('datasets.xlsx')
excel_sheets(sheets)

[1] "iris"     "mtcars"   "chickwts" "quakes"

In [7]:
finalsheet = read_excel(sheets, sheet=4)
finalsheet

     lat    long   depth mag stations
1    -20.42 181.62 562   4.8 41
2    -20.62 181.03 650   4.2 15
3    -26.00 184.10  42   5.4 43
4    -17.97 181.66 626   4.1 19
5    -20.42 181.96 649   4.0 11
6    -19.68 184.31 195   4.0 12
7    -11.70 166.10  82   4.8 43
8    -28.11 181.93 194   4.4 15
9    -28.74 181.74 211   4.7 35
10   -17.47 179.59 622   4.3 19
11   -21.44 180.69 583   4.4 13
12   -12.26 167.00 249   4.6 16
13   -18.54 182.11 554   4.4 19
14   -21.00 181.66 600   4.4 10
15   -20.70 169.92 139   6.1 94
16   -15.94 184.95 306   4.3 11
17   -13.64 165.96  50   6.0 83
18   -17.83 181.50 590   4.5 21
19   -23.50 179.78 570   4.4 13
20   -22.63 180.31 598   4.4 18
21   -20.84 181.16 576   4.5 17
22   -10.98 166.32 211   4.2 12
23   -23.30 180.16 512   4.4 18
24   -30.20 182.00 125   4.7 22
25   -19.66 180.28 431   5.4 57
26   -17.94 181.49 537   4.0 15
27   -14.72 167.51 155   4.6 18
28   -16.46 180.79 498   5.2 79
29   -20.97 181.47 582   4.5 25
30   -19.84 182.37 328   4.4 17
...  ...    ...    ...   ... ...
971  -25.79 182.38 172   4.4  14
972  -23.75 184.50  54   5.2  74
973  -24.10 184.50  68   4.7  23
974  -18.56 169.05 217   4.9  35
975  -23.30 184.68 102   4.9  27
976  -17.03 185.74 178   4.2  32
977  -20.77 183.71 251   4.4  47
978  -28.10 183.50  42   4.4  17
979  -18.83 182.26 575   4.3  11
980  -23.00 170.70  43   4.9  20
981  -20.82 181.67 577   5.0  67
982  -22.95 170.56  42   4.7  21
983  -28.22 183.60  75   4.9  49
984  -27.99 183.50  71   4.3  22
985  -15.54 187.15  60   4.5  17
986  -12.37 166.93 291   4.2  16
987  -22.33 171.66 125   5.2  51
988  -22.70 170.30  69   4.8  27
989  -17.86 181.30 614   4.0  12
990  -16.00 184.53 108   4.7  33
991  -20.73 181.42 575   4.3  18
992  -15.45 181.42 409   4.3  27
993  -20.05 183.86 243   4.9  65
994  -17.95 181.37 642   4.0  17
995  -17.70 188.10  45   4.2  10
996  -25.93 179.54 470   4.4  22
997  -12.28 167.06 248   4.7  35
998  -20.13 184.20 244   4.5  34
999  -17.40 187.80  40   4.5  14
1000 -21.59 170.56 165   6.0 119

In [8]:
library(dplyr)
library(AER)

Warning message:
"package 'dplyr' was built under R version 3.6.3"
Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Warning message:
"package 'AER' was built under R version 3.6.3"Loading required package: car
Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

Loading required package: lmtest
Warning message:
"package 'lmtest' was built under R version 3.6.3"Loading required package: zoo
Warning message:
"package 'zoo' was built under R version 3.6.3"
Attaching package: 'zoo'

The following objects are masked from 'package:base':

    as.Date, as.Date.numeric

Loading required package: sandwich
Loading required package: survival
Warning message:
"package 'survival' was built under R version 3.6.3"

In [9]:
data("Fertility")
glimpse(Fertility)

Rows: 254,654
Columns: 8
$ morekids <fct> no, no, no, no, no, no, no, no, no, no, yes, no, no, no, no, ~
$ gender1  <fct> male, female, male, male, female, male, female, male, female,~
$ gender2  <fct> female, male, female, female, female, female, male, male, mal~
$ age      <int> 27, 30, 27, 35, 30, 26, 29, 33, 29, 27, 28, 28, 35, 34, 32, 2~
$ afam     <fct> no, no, no, yes, no, no, no, no, no, no, no, no, no, no, no, ~
$ hispanic <fct> no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, n~
$ other    <fct> no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, n~
$ work     <int> 0, 30, 0, 0, 22, 40, 0, 52, 0, 0, 0, 52, 52, 52, 8, 7, 0, 40,~

In [10]:
Fertility[35:50, c('age', 'work')]

   age work
35 28  20
36 33  12
37 32   0
38 26  52
39 32  52
40 28   0
41 32  40
42 35   0
43 33   0
44 32  42
45 29   0
46 29  52
47 31   0
48 30  51
49 28   0
50 29   0

In [11]:
tail(Fertility, n=1)

       morekids gender1 gender2 age afam hispanic other work
254654 yes      female  female  35  no   no       no    0

In [12]:
count(filter(Fertility, morekids=='yes'))

  n
1 96912

In [13]:
count(filter(Fertility, gender1=='male', gender2=='male'))
count(filter(Fertility, gender1=='male', gender2=='female'))
count(filter(Fertility, gender1=='female', gender2=='male'))
count(filter(Fertility, gender1=='female', gender2=='female'))

  n
1 67799

  n
1 63185

  n
1 62724

  n
1 60946

In [14]:
#Two male children is the most common gender combination